### ISSUE TITLE
[Question] Rewrite numbers

### ISSUE THREAD

**Issue by wowi42** [fonoster/routr#102]
Hi,

Quick question, I have a provider who is sending the numbers in local format, but I need the international format for my platform. Is that possible to change the format directly inside routr?

Regards

**Comment by psanders** [comment]
Can you send an example of a number? If I understood correctly the question, we already have a draft of the feature and will be release on `rc6`.

**Comment by wowi42** [comment]
Hey @psanders 

Long story short, I have some providers (Let's say in France). They send me all numbers in the national format (0836656565), not in the international one (+33836656565).

[ Provider ] < --- > [ Routr ] < --- > [ callcenter ]

what I want is that every number between Provider and Routr, follow the national format, but every number between Router and callcenter follow the international format

Real Scenario:

- Provider forward call from +33 8366565 but formatted as 0836656565
- Routr get the call from provider, and replace 0 by +33
- Routr forward the call to callcenter


Let me know if it's not clear

**Comment by psanders** [comment]
What's on the "callcenter" side of the communication? Asterisk ? or softphone? Everything seems clear except for the outcome of rewriting the number. We are working on adding a flag that allows you to automatically match numbers to their equivalent e164. But I'm not sure it will be useful for you.

**Comment by wowi42** [comment]
callcenter is freeswitch, then verto with WebRTC (freeswitch is receiving some SIP, of course)

it could be useful, any ETA on this feature?

**Comment by psanders** [comment]
We already have a draft of the feature. How are you deploying Routr? Docker? This feature is scheduled for the next release (RC6), but I could try to release an Edge version so you can try it.

**Comment by wowi42** [comment]
@psanders we are deploying without docker (aur on archlinux)

**Comment by psanders** [comment]
Perfect. I think we can work this out. Let's continue the conversation on Slack. Find the [Get early access](https://fonoster.com/) button and complete the form. I will send you an invite so we can talk in realtime :).
