### ISSUE TITLE
ROUTR_EXTERN_ADDR

### ISSUE THREAD

**Issue by Boffice** [fonoster/routr#105]
I get bellow error in Google Shell on step 3:

```
user@cloudshell:~/cloudshell_open/routr-walkthrough-tutorial$ cd routr-1.0.0-rc4_linux-x64_bin \
>     && ./routr
Must define environment variable ROUTR_EXTERN_ADDR when running inside a container
```

**Comment by psanders** [comment]
That's outdated!  I will update to `rc5` and let you know.

**Comment by psanders** [comment]
@Boffice 

I just updated the tutorial to use the latest release. Thanks for reporting the issue!
