### ISSUE TITLE
how to set local provider

### ISSUE THREAD

**Issue by yavash** [fonoster/routr#119]
sip.provider.net is not work
how to set local provider?

**Comment by psanders** [comment]
The `sip.provider.net` is only a placeholder for a Gateway (for calling to regular phones). Routr doesn't have a concept of a "local" provider. However, if you want to create a local sip network, you could instead use `Domains`

In the future, if you have any questions, please ask the [slack community](https://form.typeform.com/to/CvQqk9). We like to keep this space for bugs only.
