### ISSUE TITLE
debian10 or centos 7  Installation problems

### ISSUE THREAD

**Issue by linlin2018** [fonoster/routr#123]
Hi, team
Can you provide a detailed installation tutorial for centos 7 or Debian 10
The installation has been a failure and is not available for novices,

**Comment by voipiran** [comment]
This is my installation guide for Centos7:
```
yum install epel-release -y
yum install snapd -y
systemctl start snapd.service
systemctl enable --now snapd.socket
ln -s /var/lib/snapd/snap /snap
snap install routr-server --candidate
```

**Comment by psanders** [comment]
Please check my answer about Snap support here: https://github.com/fonoster/routr/issues/132
