### ISSUE TITLE
Rewrite To header URI from tel: to sip:

### ISSUE THREAD

**Issue by JoyceBabu** [fonoster/routr#124]
I am trying to setup a FreePBX server. The service provider is sending tel: url in the INVITE request for inbound calls. Asterisk does not support tel: URL and responds wit `416 Unsupported URI Scheme`.

Is it possible  to setup a routr SIP proxy to rewrite the `tel:` URI in the `To:` header to `sip:`?

**Comment by psanders** [comment]
This is not possible on Routr v1. It will be in v2, but I am afraid it will be a few months before is ready.
