### ISSUE TITLE
registration with websockets does not work

### ISSUE THREAD

**Issue by dolwol** [fonoster/routr#129]
hi
i use an websocket javascript client. and it looks like routr does not answer the registration request.

i can see the request in den browers dev tools:
REGISTER sip:192.168.2.200 SIP/2.0
Via: SIP/2.0/WSS 2qigegunhi5b.invalid;branch=z9hG4bK4567235
Max-Forwards: 69
To: <sip:1002@192.168.2.200>
From: <sip:1002@192.168.2.200>;tag=l3areu9duc
Call-ID: t29ma3ru82ag48s6gg0946
CSeq: 1 REGISTER
Contact: <sip:1p8n0lr4@2qigegunhi5b.invalid;transport=ws>;+sip.ice;reg-id=1;+sip.instance="<urn:uuid:0a828c3b-a148-4db0-935f-257603c5980f>";expires=600
Expires: 600
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO,NOTIFY
Supported: path,gruu,outbound
User-Agent: JsSIP 3.9.0
Content-Length: 0

but i do not see an answer in the dev tools 
in the routr logs i see:

DEBUG] core.processor.RequestProcessor.process [route type UNKNOWN]

[DEBUG] core.processor.RequestProcessor.process [entity info null]

[DEBUG] core.processor.RequestProcessor.process [running handler for method `REGISTER`]

[DEBUG] List of gateways in quarantine: []

[DEBUG] core.processor.RegistryHandler.doProcess [via addr {"host":"172.17.0.3","port":8089}]

if i list the registed agents with rctl lcoate, i do not see the particual client.

Registrations with udp/tcp do work.

thanks for your help.

**Comment by psanders** [comment]
@dolwol 

Few questions:

- Does Routr's initial output show WSS as a transport? Are you using port `5063`?
- What happens if you use WS instead of WSS?
- Can you try using SIP.js instead (or [wPhone](https://github.com/fonoster/wphone))
- If you use wireshark or sngrep, what do you see? (For this you should use WS and no WSS)

Let me know.

**Comment by dolwol** [comment]
thanks for your answer.

- in the logs i see: [INFO ] Listening on 172.17.0.3:8089 [wss]
- With WS do not get a connection. i think mi sip javascript does not support ws, see: https://tech7fox.github.io/sip-hass-docs/docs/card/introduction
- i tried with wPhone. that worked.
- since it looks like the sip client dos not work with ws i think that dos not make sense.

i think is related to the other javascript sip client. do you have any idea why it does not work?

**Comment by psanders** [comment]
I know of people using JsSIP with Routr, but I personally never have. 

Can you show the initial output in Routr? Does it show WS as a transport?

**Comment by psanders** [comment]
I recommend enabling `ws` it for troubleshooting purposes. If it works with `ws` then you might have an issue with your tls certificates.

Which is my next question. When running JsSIP, are you also using `https`?

**Comment by dolwol** [comment]
okay, thank you. since it works with wPhone, i wil get in touch with the provider of the javascript that does not work. i cannot configure that javascritp to use ws.

**Comment by psanders** [comment]
@dolwol sounds good. But feel free to re-open the issue if needed.
