### ISSUE TITLE
java.lang.NullPointerException when creating agent with api

### ISSUE THREAD

**Issue by kovaszab** [fonoster/routr#136]
Hi!

I tried to create an Agent with the API endpoint `agents` with a post request, with the data being:
```
{
  "apiVersion": "v1beta1",
  "kind": "Agent",
  "metadata": {
    "name": "John Doe"
  },
  "spec": {
    "credentials": {
        "username": "1004",
        "secret": "1234"
    },
    "domains": [
        "plasma.lan"
    ]
  }
}
```
The response is always `{"status":400,"message":"java.lang.NullPointerException"}`.

Versions is tried:

- 1.0.5
- 1.0.3

**Comment by kovaszab** [comment]
Hi @psanders

I do not know what `rctl` is. Other api endpoints I tested worked fine (GET location, GET agents etc).

Here is the curl script I extracted from Postman: 

```
curl --location --request POST 'https://localhost:4567/api/v1beta1/agents?token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiJ9.nq3yvnNcHWKaFtZxaBqvPjWOxdTTwDP52WkuXiyB0W7xPdt_wrvU3H1O9KhU46t1AGN9beD-5soN2OQLEytC4A' \
--header 'Authorization: Basic YWRtaW46Y2hhbmdlaXQ=' \
--header 'Content-Type: application/json' \
--data-raw '{
  "apiVersion": "v1beta1",
  "kind": "Agent",
  "metadata": {
    "name": "John Doe"
  },
  "spec": {
    "credentials": {
        "username": "1004",
        "secret": "1234"
    },
    "domains": [
        "plasma.lan"
    ]
  }
}'
```

**Comment by psanders** [comment]
Thanks for the test script. I will try it asap.

Also: `rctl` is Routr's the [command-line tool](https://www.npmjs.com/package/routr-ctl).

**Comment by kovaszab** [comment]
Okay so I tried `rctl` but it doesn't works for me for some reason. I can login but I can't get any resources because it says it has none. And also I tried to import config yamls on the rctl proxy and it cannot import any saying `{"status":400,"message":"Bad request","data":"Bad configuration in at least one resource"}
[Remove file](javascript:undefined;)`. It's strange because when I list the agents for example, on the REST api it sends me back the agents and their refs, and I can also list logged in devices and so on.

**Comment by kovaszab** [comment]
Any updates on this? Or something I could help with?

**Comment by psanders** [comment]
Which data source are you using? Redis or Yaml files?

**Comment by kovaszab** [comment]
It looks like Yaml because that is the default. So I guess that means I can only create users etc with files and that is why the NullPointerException arise? I will try with Redis soon and get back to you. But I think if this is the case it would be nice to inform the user that he cannot create new resources with the CLI/API, only if they use Redis data source either in the error message or in the documentation. It makes sense though but still.

**Comment by psanders** [comment]
You are correct; that's the expected behavior.

You should have received a message indicating that the data source was unsuitable for the "create" action. We need to triage this error.
