### ISSUE TITLE
Error "Console cannot connect to running routr engine. Re-trying ..."

### ISSUE THREAD

**Issue by trojan-tj** [fonoster/routr#155]
Hello! Please help! I've been struggling with the problem for several days. The router is launched through the docker-compose (the file was taken from your github). rсtl installed via snap. There are no errors. When opening 192.168.1.35:8000, the web interface opens for a second, and then the inscription appears ... I tried installing the router via snap, rstl via npm. But the error is still the same

**Comment by psanders** [comment]
Which version of `rctl` are you using?

**Comment by trojan-tj** [comment]
rctl version
[System info]
Server version: v1.0
API version: v1beta1
API path: /api/v1beta1
[Env]
USER_AGENT=Routr v1.0.0

**Comment by psanders** [comment]
@trojan-tj can you try with `rctl --version` the other command gives info about the server side.

(Sorry for the confusion)

**Comment by trojan-tj** [comment]
rctl, version 1.0.19

**Comment by psanders** [comment]
> rctl, version 1.0.19

Please try with 1.0.20.

**Comment by psanders** [comment]
I believe we should be good here. Please reopen if after updating you still have the issue.
