### ISSUE TITLE
create agent api npt working - java.lang.NullPointerException

### ISSUE THREAD

**Issue by kmamtora** [fonoster/routr#160]
`curl --location --request POST 'https://localhost:4567/api/v1beta1/agents?token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiJ9.T7uZpNQRyqeyTbKgOasv0vtsNHq_NZVt1rbjurLNM5ieZ6pitcai2pkkSsr55nkN39-gZP-jTZgpuaGJX4t7rA' \
--header 'Authorization: Basic YWRtaW46Y2hhbmdlaXQ=' \
--form 'file=@"/Users/Downloads/agents.json"'`

response 

`{"status":400,"message":"TypeError: jsonObjs.forEach is not a function"}`

even tried this

`rctl create -f agents.yml`
`java.lang.NullPointerException`

agnets.yml file
`---
  apiVersion: "v1beta1"
  kind: "Agent"
  metadata: 
    name: "Karan"
  spec: 
    credentials: 
      username: "1005"
      secret: "1234"
    domains: 
      - "sip.local"`

**Comment by kmamtora** [comment]
any update ?

**Comment by psanders** [comment]
@kmamtora it seems like the `agents.yml` file is malformed and we are not validating the input which makes the error confusing. Can you double check the formating of your yaml? [Example](https://github.com/fonoster/routr/blob/v1/config/agents.yml).

**Comment by kmamtora** [comment]
Hi @psanders, Happy New Year!!


I am still not able to create new agents it shows same error. I check the above example formatting is proper, even i copied and tried to create new agents it still gives same error

**Comment by psanders** [comment]
@kmamtora uff sorry you are having this issues. I will try to reproduce this sometime today.

**Comment by psanders** [comment]
@kmamtora Can you try the request using `Content-Type: application/json`?

I'm able to send request with out issues.

<img width="1026" alt="request" src="https://user-images.githubusercontent.com/539774/210678928-bf20fbcf-f1ed-4194-8bf0-cf77c1e9b159.png">

I will keep this open, until we fix the errors.

**Comment by kmamtora** [comment]
hi @psanders, I have added Content-Type: applicaiton/json

still having same issue

![image](https://user-images.githubusercontent.com/44718980/211240194-5004101d-b010-4b83-8bb4-60f86f07880c.png)

**Comment by psanders** [comment]
Have you created a the `sip.local` domain? I am out of ideas.

**Comment by kmamtora** [comment]
hi @psanders not it gives Invalid address! Must be a valid Ipv4 or Ipv6

**Comment by psanders** [comment]
I'm sorry that this conversation has been inactive for a while. I'd be more than happy to pick up where we left off and assist you further. However, I will need additional context to better understand the issue and provide a more accurate solution.

For now, I will close the conversation, but if the problem persists, don't hesitate to reach out to me again. I'll be happy to re-open the conversation and continue helping you.
