### ISSUE TITLE
Is there any configuration about concurrent calls(or simultaneous calls)?

### ISSUE THREAD

**Issue by Lizz850517** [fonoster/routr#164]
Hi, I am glad to found this project and very appreciate for your effort!
I'm wondering the concurrent calls is configurable or not?
or is it doesn't have any limits, I can call(and keep in calling state) as many calls in a period of time as my computer can afford?

**Comment by psanders** [comment]
@Lizz850517 If you are running on a single node (e.g, using Docker Compose), it can only scale vertically. However, you can run Routr in the cloud with Kubernetes and scale it vertically and horizontally.
