### ISSUE TITLE
External Sql and No Sql database support

### ISSUE THREAD

**Issue by AlijiEmmanuel-dev** [fonoster/routr#178]
Currently it is very difficult to share data from Routr with other system, this is primarily because there is no external database support. This is great project, and I expect more people to use it within the coming years. on of the challenges that will be faced will be embedding Routr into existing systems where data sharing have to be seamless. My current use case have been to work around with the file system, but I don't think that is efficient.

I suggest adding a data abstraction layer that allows external database integration in such a way that will allow engineers build connectors for their preferred database if it is not available. This will provide maximum data interoperability withing systems. 

Another way is to provide an interface that allow developers work directly with the file system. This can be done by allowing developer access the file system data source through an API that exposes the files itself, or a connector that allows direct commands to be sent to the in memory database.

I really hope to hear from you, and I will love to be of help.

**Comment by psanders** [comment]
Hi @AlijiEmmanuel-dev,

I completely agree with you, all the desirable features have been added in Routr v2 (beta), including the capability of having pluggable data services. Currently, there are two data modules available: simpedata (YAML files) and pgdata (Postgres). However, the gRPC interface allows future support for any data source.

We also have ta Node SDK and a CLI available in v2.

Unfortunately, it will take some time before the docs are ready.

**Comment by AlijiEmmanuel-dev** [comment]
Thank you so much @psanders , I really appreciate your great work.
Please, is there a way I can start using version 2 and also contribute to the documentation.
I will really love to start working on it right away.

**Comment by psanders** [comment]
@AlijiEmmanuel-dev for sure. Feel free to join the Discord [community](https://discord.gg/mpWSRUhG7e). We should be able to help unblock you.
