### ISSUE TITLE
helm routr/routr-connect not working

### ISSUE THREAD

**Issue by 406112767** [fonoster/routr#185]
**Describe the bug**
use helm install routr/routr-connect，chart version: 0.15,  app version: 2.0.34.  can't pull image fonoster/routr-connect:2.0.34.
I also can't find the image in hub.docker.com

**Comment by psanders** [comment]
@406112767 would you try again with `0.1.5`?

![Screenshot 2023-06-17 at 12 37 58 AM](https://github.com/fonoster/routr/assets/539774/f92ee42e-4d28-40f2-bb40-a2b99d486ae2)

**Comment by 406112767** [comment]
@psanders helm works，but some image have error.
such as fonoster/routr-pgdata:2.1.2
<img width="931" alt="image" src="https://github.com/fonoster/routr/assets/32954251/5eb0dd2d-10e7-47cc-90ee-5fa317e8c7c0">
fonoster/routr-edgeport:2.1.2
<img width="1391" alt="image" src="https://github.com/fonoster/routr/assets/32954251/f2db4e85-5e11-4567-a093-1e99ebeba928">

**Comment by 406112767** [comment]
@psanders sometimes statefulset.apps/sipnet-routr-edgeport check /healthz error 
 need to delay the livenessProbe health check time

**Comment by psanders** [comment]
@406112767 would you try chart `0.1.6`? I released a version that should fixes those issues. I recommend starting a fresh installation and download the latest command-line version.

**Comment by 406112767** [comment]
@psanders it works，thank you.

**Comment by psanders** [comment]
@406112767 thank you.
