### ISSUE TITLE
rctl proxy -> Routr Console -> logs gives error

### ISSUE THREAD

**Issue by eagle-one78** [fonoster/routr#228]
**Describe the bug**
In Routr Console when clicked on "Logs" error occur 

**To Reproduce**
1. CMD rtcl proxy
2. enter browser version of Routr Console
3. Click on "Logs"
5. See error in the powershell

**Expected behavior**
Logs should appear without error
**Screenshots**
![image](https://github.com/fonoster/routr/assets/1241595/5d9d9687-1665-44e2-b6aa-3c3d3d059500)

![image](https://github.com/fonoster/routr/assets/1241595/5aaaa1ce-8daa-4a1e-b8b6-0e5a21b3a117)

**System information (please complete the following):**
 - OS: [e.g. Linux]
 - NodeJS, NPM versions [e.g. v14.16.0, 7.10.0]
 - CTL version [e.g. 0.1 ]

**Additional context**
[ERROR] org.eclipse.jetty.websocket.api.UpgradeException: Failed to upgrade to websocket: Unexpected HTTP Response Status Code: 404 Not Found
[ERROR] org.eclipse.jetty.websocket.api.UpgradeException: Failed to upgrade to websocket: Unexpected HTTP Response Status Code: 404 Not Found
[ERROR] java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.websocket.api.Session.isOpen()" because "this.remoteSession" is null

**Comment by psanders** [comment]
I'm closing this issue as we are not longer supporting the [routr-ui.](https://github.com/fonoster/routr-ui)
