### ISSUE TITLE
Issue with @router/common/src... when build SDK

### ISSUE THREAD

**Issue by dimusa6** [fonoster/routr#233]
Hello, I'm creating a project with routr/sdk, and when I tried to build always give me this error:

"node_modules/@routr/sdk/dist/client.d.ts:2:44 - error TS2307: Cannot find module '@routr/common/src/connect' or its corresponding type declarations."

2 import { APIClient as ConnectClient } from "@routr/common/src/connect";"

It seems that search about routr/common/src folder and it doesn't exist, like in this line:
https://github.com/fonoster/routr/blob/fc0be57a79d61e96349757e1ddf19cbbe8d6fcff/mods/sdk/src/client.ts#L23

Following the structure about npm package routr/common repo, Should it change dist to src folder maybe? 

Thanks for this awesome SIP server

**Comment by psanders** [comment]
Having "src" in the path looks quite suspicious. I'm actually surprised this is the first time it's been reported. 

That being said, I will be very engaged until around November 3rd and don't think I will have time to fix this. 

Would you be able to submit a PR for this?
