### ISSUE TITLE
Allow to add gateway without registration

### ISSUE THREAD

**Issue by vitalyster** [fonoster/routr#24]
My SIP provider does not provide credentials and works for example with freeswitch and `  <param name="register" value="false"/>`, while your gateway spec requires it.

**Comment by psanders** [comment]
- [ ]

**Comment by vitalyster** [comment]
Does it fixed or not planned anymore? :)

**Comment by psanders** [comment]
This issue went cool so I decided to closed. I'm going to take another look at this. Feel free to share any RFCs that support this feature.

**Comment by psanders** [comment]
This feature was added in the graalvm-exp branch an tested against [voip.ms](https://voip.ms). It will be available RC3 and the documentation will be updated accordingly.

> To use this feature it is important to have the [spec.externAddr and spec.localnets](https://routr.io/docs/configuration/general/) properly configure.

I'm closing this for now. Feel free to ask any question or re-open.
