### ISSUE TITLE
How to implement Routr proxy freeswitch

### ISSUE THREAD

**Issue by happytulubi** [fonoster/routr#270]
I have configured two agents 1001 and 1002 in Routr, and 1001 can be used to call 1002. But I want to use the Routr proxy for freeswitch, for example, when registering with 1001, it will first be sent to Routr, and then Routr will proxy the registration message to freeswitch. Can it be implemented and how to configure it.

**Comment by psanders** [comment]
It is possible, but you would need to build a middleware or [processor.](https://github.com/fonoster/nodejs-processor), and sadly, we don't have much documentation on this topic.
