### ISSUE TITLE
centos7 installation error

### ISSUE THREAD

**Issue by linlin2018** [fonoster/routr#42]
[WARN ] Unable to register with Gateway -> sip.provider.net. (Verify your network status)

**Comment by psanders** [comment]
Your Routr installation is still using the example configuration in the gateways.yml file which is still pointing to a fake domain. This will disappear if you remove the Gateway or use a valid domain as your Gateway/Provider.

**Comment by linlin2018** [comment]
Another problem：”javax.sip.TransactionUnavailableException: Cannot find matching Subscription (and gov.nist.javax.sip.DELIVER_UNSOLICITED_NOTIFY not set“”
