### ISSUE TITLE
custom variant sip interaction

### ISSUE THREAD

**Issue by moggle-mog** [fonoster/routr#47]
Can I custom variant sip interaction like kamailio ？

**Comment by moggle-mog** [comment]
Thank you for your reply,

We use special sip devices, it will send `keepalive` to sip server with method `message`, we want to unpack this message and reply `200OK` or do routing.

**Comment by psanders** [comment]
It does not sound very complex but not sure I understand the use case. If you think it is a common use case you can send a feature request with more detail we will consider adding it to next release.

**Comment by moggle-mog** [comment]
Sorry, I can't find `feature request` anywhere.

Now I will implement a special sip server to respond special sip request, it represent `peer` and its topology like below:
special sip client(as agent) ---> routr ---> special sip server(as peer)

I think it is a common use case like `kamailio`, user can use routr as a powerful and extensible sip framework.

**Comment by psanders** [comment]
@moggle-mog I added "extensibility" as a key topic for the next [milestone](https://github.com/fonoster/routr/issues/46). My goal is to allow creation of plugins that overwrite the server's behavior. Please join the [conversation](https://github.com/fonoster/routr/issues/46) to help influence this area work.

**Comment by psanders** [comment]
I'm closing this issue, since it will be address in another [conversation](https://github.com/fonoster/routr/issues/46).
