### ISSUE TITLE
run routr cause error

### ISSUE THREAD

**Issue by moggle-mog** [fonoster/routr#62]
version: Routr 1.0 RC4 (Draft)

cmd: 
``` ./routr```

error info:   
 ```
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider com.oracle.truffle.js.scriptengine.GraalJSEngineFactory could not be instantiated
Unable to run server [Invalid js engine => 'graal.js'
```

**Comment by psanders** [comment]
Are you trying to compile from source? If you download from the [distro](https://github.com/fonoster/routr#custom) page it will have a JRE that supports graal.js. Otherwise, the `routr` script will attempt use whatever runtime is available on the host machine.

**Comment by moggle-mog** [comment]
I use `rc4` from `release` page,maybe `rc4` need JRE that support graal.js?

**Comment by psanders** [comment]
If you download from the release page it comes with JRE which supports Graal. I’m going to do more test today.

**Comment by moggle-mog** [comment]
Thanks, rc4:`https://github.com/fonoster/routr/releases/tag/1.0.0-rc4`

**Comment by psanders** [comment]
I was able to reproduce and fix this issue. The binaries will be updated in few hours. Feel free to re-open if still see this error.
