### ISSUE TITLE
The Readme: typo / bad English

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [fonoster/routr#63]
'It also provides with capabilities' should be, 'Also, it provides capabilities'. (The main problem is the 'with' - for, that word should not be there. Additionally, though, 'It also provides' splits the parts of the verb. The form of words that I suggest fixes both those problems.)

**Comment by psanders** [comment]
Wao! Grammarly didn't told me that :/
I updated the document with your recommendation. 

Thanks a lot!
