### ISSUE TITLE
It's Server or Proxy [Question]

### ISSUE THREAD

**Issue by ramosisw** [fonoster/routr#64]
Can I use 'router' as a standalone?

**Comment by psanders** [comment]
Most definitely. What is your use case?

**Comment by ramosisw** [comment]
For personal use, but my question is, is an additional SIP server necessary?

I currently see in the log: could not establish communication with `sip.local`

**Comment by psanders** [comment]
You don't need an additional SIP server. That log typically means that you need to add a [Domain](https://routr.io/docs/configuration/domains/). You can verify your current configuration using the [command-line tool](https://routr.io/docs/administration/cli/installation/).

**Comment by psanders** [comment]
I'm closing this. Feel free to re-open if you have any question.
