### ISSUE TITLE
Is it similar to flexisip

### ISSUE THREAD

**Issue by ugintl** [fonoster/routr#65]
I want to build something similar to skype. Can routr help me achieve it?

Users will register an account and have username something like user@mydomain.com

**Comment by psanders** [comment]
I'm not familiar with Flexisip, but you can definitely use Routr as part of your "skype-like" infrastructure.

**Comment by HumzaAli55** [comment]
@psanders  flexisip is a sip server which can be used with linphone client. What do you mean by part of your "skype-like" infrastructure?
