### ISSUE TITLE
Connection to the websocket refused

### ISSUE THREAD

**Issue by philiplb** [fonoster/routr#70]
Hi,

I have a sip.js application here which I want to let connect to a routr instance.
But it fails to connect to the websocket with this message:

> WebSocket connection to 'wss://....com:5063/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

I've setup the certificates and have manually entered the wss port in the network settings.

Telnet doesn't work either and a `listen -al | grep LISTEN` shows that the port 5063 isn't open.

Do you have any clue here?

**Comment by psanders** [comment]
When you start Routr does it show all the ports initial setup? Like this:

<img width="386" alt="Screen Shot 2020-03-26 at 9 50 42 AM" src="https://user-images.githubusercontent.com/539774/77654307-49382980-6f47-11ea-8420-b013969a27fa.png">

**Comment by philiplb** [comment]
Thanks!
How do I (re)start it? Currently it is running as whatever daemon the Snap installation has setup.

**Comment by psanders** [comment]
Use `rctl system restart`

**Comment by philiplb** [comment]
Thx.
This is the from the log, yet I still can't connect to 5063:

> [INFO ] 2020-03-26 14:19:54.290 [main] MHBase - Starting Routr
> [INFO ] 2020-03-26 14:19:54.346 [main] routr - using Enabled tls auth policy
> [WARN ] 2020-03-26 14:19:55.078 [main] routr - using default tls security policy
> [INFO ] 2020-03-26 14:19:55.080 [main] routr - javax.net.ssl.trustStorePassword is null, using the password passed through javax.net.ssl.keyStorePassword
> [WARN ] 2020-03-26 14:19:55.081 [main] routr - Using default truststore type jks
> [INFO ] 2020-03-26 14:19:55.444 [main] MHBase - Listening on 172.31.26.131:5060 [udp]
> [INFO ] 2020-03-26 14:19:55.476 [main] MHBase - Listening on 172.31.26.131:5060 [tcp]
> [INFO ] 2020-03-26 14:19:55.485 [main] MHBase - Listening on 172.31.26.131:5063 [wss]
> [DEBUG] 2020-03-26 14:19:57.238 [main] InternalLoggerFactory - Using Log4J as the default logging framework
> [DEBUG] 2020-03-26 14:19:57.243 [main] PlatformDependent0 - -Dio.netty.noUnsafe: false
> [DEBUG] 2020-03-26 14:19:57.243 [main] PlatformDependent0 - Java version: 8
> [DEBUG] 2020-03-26 14:19:57.244 [main] PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
> [DEBUG] 2020-03-26 14:19:57.245 [main] PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
> [DEBUG] 2020-03-26 14:19:57.246 [main] PlatformDependent0 - java.nio.Buffer.address: available
> [DEBUG] 2020-03-26 14:19:57.246 [main] PlatformDependent0 - direct buffer constructor: available
> [DEBUG] 2020-03-26 14:19:57.247 [main] PlatformDependent0 - java.nio.Bits.unaligned: available, true
> [DEBUG] 2020-03-26 14:19:57.247 [main] PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
> [DEBUG] 2020-03-26 14:19:57.247 [main] PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
> [DEBUG] 2020-03-26 14:19:57.248 [main] PlatformDependent - sun.misc.Unsafe: available
> [DEBUG] 2020-03-26 14:19:57.248 [main] PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
> [DEBUG] 2020-03-26 14:19:57.248 [main] PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
> [DEBUG] 2020-03-26 14:19:57.250 [main] PlatformDependent - -Dio.netty.maxDirectMemory: 245301248 bytes
> [DEBUG] 2020-03-26 14:19:57.250 [main] PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
> [DEBUG] 2020-03-26 14:19:57.251 [main] CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
> [DEBUG] 2020-03-26 14:19:57.251 [main] PlatformDependent - -Dio.netty.noPreferDirect: false
> [DEBUG] 2020-03-26 14:19:57.262 [main] MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 4
> [DEBUG] 2020-03-26 14:19:57.290 [main] NioEventLoop - -Dio.netty.noKeySetOptimization: false
> [DEBUG] 2020-03-26 14:19:57.290 [main] NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
> [DEBUG] 2020-03-26 14:19:57.301 [main] PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
> [INFO ] 2020-03-26 14:19:57.375 [main] MHBase - Starting Restful service (port: 4567, apiPath: /api/v1beta1)

**Comment by psanders** [comment]
I'm unable to replicate this issue :| 

<img width="675" alt="Screen Shot 2020-03-26 at 10 36 32 AM" src="https://user-images.githubusercontent.com/539774/77658875-b8b11780-6f4d-11ea-8885-5ab6061d4efc.png">

I wonder if it has anything to do with Snap. Are you only having issues with WSS?

**Comment by philiplb** [comment]
Hm, I don't get anything at the moment when executing lsof.
And I can't restart routr anymore?

> rctl system restart
> Unable to perform request. Ensure server is up!

**Comment by psanders** [comment]
I gout you. Check the status of the Snap Service and restart in needed.

`sudo snap services`
`sudo snap restart routr-server.routr-server`

**Comment by psanders** [comment]
Any luck with it this?

**Comment by philiplb** [comment]
Hi @psanders ,

I'm afraid not, here is what I did:

> ubuntu@ip-172-31-26-131:~$ sudo snap services
> Service                            Startup  Current   Notes
> amazon-ssm-agent.amazon-ssm-agent  enabled  active    -
> routr-server.routr-redis           enabled  active    -
> routr-server.routr-server          enabled  inactive  -
> ubuntu@ip-172-31-26-131:~$  sudo snap restart routr-server.routr-server
> Restarted.
> ubuntu@ip-172-31-26-131:~$ sudo snap services
> Service                            Startup  Current  Notes
> amazon-ssm-agent.amazon-ssm-agent  enabled  active   -
> routr-server.routr-redis           enabled  active   -
> routr-server.routr-server          enabled  active   -
> ubuntu@ip-172-31-26-131:~$ lsof -i :5060
> ubuntu@ip-172-31-26-131:~$ lsof -i :5061
> ubuntu@ip-172-31-26-131:~$ lsof -i :5063
> ubuntu@ip-172-31-26-131:~$ netstat -al | grep LISTEN
> tcp        0      0 localhost:domain        0.0.0.0:*               LISTEN
> tcp        0      0 0.0.0.0:ssh             0.0.0.0:*               LISTEN
> tcp        0      0 0.0.0.0:8000            0.0.0.0:*               LISTEN
> tcp        0      0 0.0.0.0:6379            0.0.0.0:*               LISTEN
> tcp6       0      0 [::]:ssh                [::]:*                  LISTEN
> tcp6       0      0 [::]:6379               [::]:*                  LISTEN
> unix  2      [ ACC ]     SEQPACKET  LISTENING     11921    /run/udev/control
> unix  2      [ ACC ]     STREAM     LISTENING     896240   /run/user/1000/systemd/private
> unix  2      [ ACC ]     STREAM     LISTENING     896244   /run/user/1000/gnupg/S.gpg-agent
> unix  2      [ ACC ]     STREAM     LISTENING     896245   /run/user/1000/snapd-session-agent.socket
> unix  2      [ ACC ]     STREAM     LISTENING     896246   /run/user/1000/gnupg/S.gpg-agent.browser
> unix  2      [ ACC ]     STREAM     LISTENING     896247   /run/user/1000/gnupg/S.gpg-agent.extra
> unix  2      [ ACC ]     STREAM     LISTENING     896248   /run/user/1000/gnupg/S.dirmngr
> unix  2      [ ACC ]     STREAM     LISTENING     896249   /run/user/1000/gnupg/S.gpg-agent.ssh
> unix  2      [ ACC ]     STREAM     LISTENING     16056    @irqbalance803.sock
> unix  2      [ ACC ]     STREAM     LISTENING     16523    /var/lib/lxd/unix.socket
> unix  2      [ ACC ]     STREAM     LISTENING     16487    /run/acpid.socket
> unix  2      [ ACC ]     STREAM     LISTENING     16496    /run/snapd.socket
> unix  2      [ ACC ]     STREAM     LISTENING     16498    /run/snapd-snap.socket
> unix  2      [ ACC ]     STREAM     LISTENING     16517    /run/uuidd/request
> unix  2      [ ACC ]     STREAM     LISTENING     15947    /var/run/dbus/system_bus_socket
> unix  2      [ ACC ]     STREAM     LISTENING     15930    @ISCSIADM_ABSTRACT_NAMESPACE
> unix  2      [ ACC ]     STREAM     LISTENING     11754    /run/systemd/private
> unix  2      [ ACC ]     STREAM     LISTENING     11759    /run/systemd/journal/stdout
> unix  2      [ ACC ]     STREAM     LISTENING     11868    /run/lvm/lvmetad.socket
> unix  2      [ ACC ]     STREAM     LISTENING     11916    /run/lvm/lvmpolld.socket

**Comment by psanders** [comment]
I know is a long shot, but will running `sudo lsof -i :5060` yield different results? I cant think on a reason why the server is not listening but is "active."

**Comment by psanders** [comment]
Can you share your `/var/snap/routr-server/current/logs/routr.log` restarting?

**Comment by philiplb** [comment]
@psanders 
Hi,

thanks for investigating!

This is my log after a `sudo snap restart routr-server.routr-server`:

```
[WARN ] 2020-04-01 09:35:13.324 [main] MHBase - java.io.FileNotFoundException: config/stack.properties (No such file or directory)
[INFO ] 2020-04-01 09:35:13.390 [main] MHBase - Starting Routr
[INFO ] 2020-04-01 09:35:13.465 [main] routr - using Enabled tls auth policy
[WARN ] 2020-04-01 09:35:14.274 [main] routr - using default tls security policy
[INFO ] 2020-04-01 09:35:14.286 [main] routr - javax.net.ssl.trustStorePassword is null, using the password passed through javax.net.ssl.keyStorePassword
[WARN ] 2020-04-01 09:35:14.287 [main] routr - Using default truststore type jks
[INFO ] 2020-04-01 09:35:14.628 [main] MHBase - Listening on 172.31.26.131:5060 [udp]
[INFO ] 2020-04-01 09:35:14.656 [main] MHBase - Listening on 172.31.26.131:5060 [tcp]
[INFO ] 2020-04-01 09:35:14.661 [main] MHBase - Listening on 172.31.26.131:5063 [wss]
[DEBUG] 2020-04-01 09:35:16.586 [main] InternalLoggerFactory - Using Log4J as the default logging framework
[DEBUG] 2020-04-01 09:35:16.590 [main] PlatformDependent0 - -Dio.netty.noUnsafe: false
[DEBUG] 2020-04-01 09:35:16.590 [main] PlatformDependent0 - Java version: 8
[DEBUG] 2020-04-01 09:35:16.591 [main] PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
[DEBUG] 2020-04-01 09:35:16.592 [main] PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
[DEBUG] 2020-04-01 09:35:16.593 [main] PlatformDependent0 - java.nio.Buffer.address: available
[DEBUG] 2020-04-01 09:35:16.593 [main] PlatformDependent0 - direct buffer constructor: available
[DEBUG] 2020-04-01 09:35:16.594 [main] PlatformDependent0 - java.nio.Bits.unaligned: available, true
[DEBUG] 2020-04-01 09:35:16.594 [main] PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
[DEBUG] 2020-04-01 09:35:16.594 [main] PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
[DEBUG] 2020-04-01 09:35:16.594 [main] PlatformDependent - sun.misc.Unsafe: available
[DEBUG] 2020-04-01 09:35:16.595 [main] PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
[DEBUG] 2020-04-01 09:35:16.595 [main] PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
[DEBUG] 2020-04-01 09:35:16.596 [main] PlatformDependent - -Dio.netty.maxDirectMemory: 245301248 bytes
[DEBUG] 2020-04-01 09:35:16.597 [main] PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
[DEBUG] 2020-04-01 09:35:16.598 [main] CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
[DEBUG] 2020-04-01 09:35:16.598 [main] PlatformDependent - -Dio.netty.noPreferDirect: false
[DEBUG] 2020-04-01 09:35:16.609 [main] MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 4
[DEBUG] 2020-04-01 09:35:16.634 [main] NioEventLoop - -Dio.netty.noKeySetOptimization: false
[DEBUG] 2020-04-01 09:35:16.635 [main] NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
[DEBUG] 2020-04-01 09:35:16.643 [main] PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
[INFO ] 2020-04-01 09:35:16.696 [main] MHBase - Starting Restful service (port: 4567, apiPath: /api/v1beta1)
```

Afterwards, `sudo lsof -i :5060` still has no output and an exit code of "1".

What I could also offer here, if you are interested (I don't want to steal your time!): If you give me a public key and your (current) IP address, I could give you direct access to the server. You can send this information to me via philip@philiplb.de.

**Comment by psanders** [comment]
I published a fix for this in the Edge channel of the Snapstore, as well as in the Docker Hub. 

There is another [unrelated issue](https://github.com/fonoster/routr/issues/74) with SIP.js that will affect your deployment. I'm closing this for now, but feel free to reopen if this issue reoccurs.

**Comment by philiplb** [comment]
Awesome, I will give it a try right next week when I'm back to work. Thanks!
