### ISSUE TITLE
Connect to routr without proxy

### ISSUE THREAD

**Issue by szenciattila** [fonoster/routr#72]
Hi Guys!

First of all, I would like to thank you for your work, I'm glad someone is working on a "2020 compatible" SIP.
I hope I'm just doing something wrong, but I need some help.

I would like to connect a HikVision IP Intercom to Routr but the device, cannot take any configuration data for proxy, as you seen on the following picture:

![image](https://user-images.githubusercontent.com/32485179/77857703-757dcf80-71ff-11ea-8383-8560b1a02e10.png)

The goal would be for Intercom to be able to call numbers within a single domain.
I already managed it to work with Asterisk (without proxy), but I would like to use a Routr as only service for SIP.

Thank you in advance for your reply.

Attila

**Comment by psanders** [comment]
@szenciattila

I'm not familiar with the device, but you could try to set your `Server Domain` to Routr's IP address and in the `Login Username` use the Agent you created in Routr @ the Domain(i.e `john@sip.local`)

**Comment by szenciattila** [comment]
Thank you @psanders for the fast response!

Unfortunately, the device cannot accept username with a special character, so "1001@sip.local" was rejected :(

Is there any other way to bypass the domain?
Or some not too complicated solution?
