### ISSUE TITLE
Better documentation: Installed, and then?

### ISSUE THREAD

**Issue by TheNomad11** [fonoster/routr#80]
Routr is supposed to be easy to install. I installed it with snap, but then what to do next? I cannot find any information. Please add some information for non sys-admins, thanks!

**Comment by psanders** [comment]
Everything you need from installation to deployment you will find at [routr.io](https://routr.io/docs/introduction/installation/). If you find gap in the documentation, please let me know and I will happily update.

**Comment by psanders** [comment]
I hope you find the information you needed. I'm closing this for now, but you can re-open if necessary.
