### ISSUE TITLE
Is there a way to manipulate incoming SIP messages in any way ?

### ISSUE THREAD

**Issue by vasilakisfil** [fonoster/routr#90]
Hi, investigating if routr will actually help me on something that I am building. I was wondering if there is a way to manipulate SIP messages (requests or responses) in some way.. ?

**Comment by psanders** [comment]
Hi @vasilakisfil 

Unfortunately, the current version of Routr is not customizable at that level. I'm working on a spec to allow for plugins, but I can't give a roadmap for when it will be ready. 

What's your use case?

**Comment by vasilakisfil** [comment]
Well many things, I want to implement a custom SIP extension/feature through rfc6809, implement a custom blocklist based on a 3rd party system (so, dynamic), etc. It would be super cool to build something using routr, in Kamailio the whole development process is extremely outdated and painful.

**Comment by psanders** [comment]
Wao! That's exactly what I have in mind for[ v1.1](https://github.com/orgs/fonoster/projects/5). Kamailio offers a lot of flexibility (which Routr at the moment lacks) but it is very outdated. I know v1.1 is going to reshape the SIP Server space.

**Comment by psanders** [comment]
Let's take the conversation to [Slack](https://join.slack.com/t/fonoster/shared_invite/enQtODc2NDY5ODA3NzYzLTNjOTRmZDQ5NzgzZjQ1MTQ3ZDQzNTgwOGVjMzIzYTkwNjZlMWU0ZmZjODMxYjIzODJjZGIwY2FiODA3YjU4ZTk). In think the community will be interested in a more modular/flexible Routr :)
