### ISSUE TITLE
Empty peers.yml causes error on startup

### ISSUE THREAD

**Issue by envy** [fonoster/routr#92]
When having an empty peer file, routr will not start and will only print this unhelpful message:

```
[ERROR] com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (StringReader); line: 9, column: 21]
```

My peer file wasn't completely empty, therefore the non-1 line and column numbers (it only contained comments), but an empty peers.yml causes the same error.

If peers really needs to contain something, then the error should reflect (a) that and (b) it should say that the error happened while reading peers.yml.

**Comment by psanders** [comment]
I will take a look at this. Can you tell which version are you using?

**Comment by envy** [comment]
I was using 1.0 RC5
