### ISSUE TITLE
Gateway: Define Outbound Proxy Server

### ISSUE THREAD

**Issue by markcs** [fonoster/routr#94]
Is it possible to define the outbound proxy server in the Gateway config?  This is required for some SIP providers

for example, sip2sip requires the following info:

```
SIP Address | sip:myusername@sip2sip.info
Username | myusername
Domain/Realm | sip2sip.info
Outbound Proxy | proxy.sipthor.net
```

**Comment by psanders** [comment]
What distribution of Routr are you using? If you are using docker, for example, you could try overwriting the file `stack.properties` located in the `config` folder of the server. The property you are looking for is `javax.sip.OUTBOUND_PROXY`. The format for this string is "ipaddress:port/transport" i.e. 129.1.22.333:5060/UDP.

I never use this property before, so please let me know if it works. Maybe we can add the property as a spec in the `config.yml.`

**Comment by markcs** [comment]
I'm using Ubuntu and the tar file from github.

Normally the outbound proxy is set per SIP provider, so this would have to be defined in the gateway.yml file and not globally.  I can try your suggestion and report back.
