### ISSUE TITLE
Usage of gateways.yml

### ISSUE THREAD

**Issue by peymanh** [fonoster/routr#96]
Hi. We have read your official documentation. Your definition of _Gateway_ in Glossary is not clear enough for us.
Would you please give us more information about its usage?
In `/opt/routr/config/gateways.yml`, What is `sip.provider.net`? Do we need to run anything else?

We want to run `routr` service with minimum configuration so we define the services like this [docker compose](https://github.com/fonoster/routr/blob/master/docker-compose.yml). But the `routr` service is not working properly, giving us some warning like  this:

`[WARN ] Unable to connect to host -> <OUR_IP>.(Verify your network status)`

Do we need to add some more configuration? Is there anything missing in that docker compose file?

**Comment by psanders** [comment]
Hi Peyman!

Your definition of *Gateway* in Glossary is not clear enough for us.


A Gateway is a service provider like voip.ms, which you will only need to
call to a plain-old-phone.

Do we need to add some more configuration? Is there anything missing in
> that docker compose file?


It depends on your use case. If you need a simple phone system for your
home or office, please check this guide
<https://pedrosanders.medium.com/tutorial-getting-started-with-routr-sip-server-f66c5216690a>
.

--
Sanders

**Comment by peymanh** [comment]
Thanks @psanders. I read the link you sent. 

Our agents are not in a same network. So `routr + TURN/STUN` are not enough for an agent to call another agent on the public internet?
And should we run another service like `freepbx` for this purpose?

**Comment by psanders** [comment]
If all you are doing is SIP calling, Routr will do the job even if your agents are on the public internet.
