### ISSUE TITLE
How to configure an instance installed with snap

### ISSUE THREAD

**Issue by raffomania** [fonoster/routr#97]
When installing using snap, the routr installation is in `/snap/routr-server`, but I can't change the configs there because it's a read-only filesystem. Where do I put the files instead?

**Comment by psanders** [comment]
@raffomania 

The snap distro stores the config on a Redis server instead of files. You can use the `rctl` tool in order to add `Agents`, `Domains`, etc.

Sorry for the late response.

**Comment by raffomania** [comment]
thanks for the info! might be useful to include this in the docs :)
