### ISSUE TITLE
Routr docker not booting up

### ISSUE THREAD

**Issue by nyxnyx** [fonoster/routr#98]
Hi,
I'm running routr with docker using following commandline:
```
docker run -it \
    -p 4567:4567 \
    -p 5060:5060 \
    -p 5060:5060/udp \
    -e EXTERN_ADDR=`curl ifconfig.co` \
    -e DATA_SOURCE_PROVIDER=files_data_provider \
    -v $(pwd)/config:/opt/routr/config \
    fonoster/routr
```
with config mounted locally with default content.
The routr exits with error: 
```
[INFO  tini (1)] Main child exited normally (with status '0')
[INFO  tini (1)] Spawned child process './routr' with pid '9'
[ERROR] com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (StringReader); line: 19, column: 20]
[INFO  tini (1)] Main child exited normally (with status '0')
```
What am I missing?

**Comment by nyxnyx** [comment]
Got it - I don't have gateways.yml configured. But this is what I want - I want only alone routr instance to make calls using sip within it. Is it possible?

**Comment by psanders** [comment]
Hey! @nyxnyx 

Yes, you can use Routr without using gateways. That Is a legit use case. We do have a [pending issue](https://github.com/fonoster/routr/issues/92) that causes Routr to fail to start if there is a missing config file. I'm closing this, but feel free to continue the conversation at [#92](https://github.com/fonoster/routr/issues/92)
