### ISSUE TITLE
helm charts return 404

### ISSUE THREAD

**Issue by hgye** [fonoster/routr#99]
![截屏2021-02-02 上午11 17 14](https://user-images.githubusercontent.com/497873/106547520-513dfe00-6548-11eb-9d99-d3aea3734777.png)

**Comment by psanders** [comment]
Hi @hgye 

I finally made it to this issue. You will find that accessing `/charts` directly from the browser will yield a `404` since there is no index.html there. Instead, you could use [Artifact Hub](https://artifacthub.io/packages/helm/routr/routr) to view the chart.

**Comment by hgye** [comment]
I just make it working and write a gist for others ref:
https://gist.github.com/hgye/644bfaa8157108d6c203ce22b5f17814

**Comment by psanders** [comment]
This is very very interesting. Thanks for sharing!
--
Pedro
